# These are supported funding model platforms if you would like to fund to Force Sub Bot Development.

github: RoyalDevendra, loverboyXD
custom: https://telegram.me/Royal_Devendra, https://telegram.me/loverboyXD, https://telegram.me/Legend_Cyrus
