# These are supported funding model platforms if you would like to fund to Force Sub Bot Development.

github: github.com/RoyalDevendra, loverboyXD
github: github.com/loverboyXD
custom: https://telegram.me/Royal_Devendra
custom: https://telegram.me/loverboyXD
custom: https://telegram.me/Legend_Cyrus
